[tool.poetry]
name = "course-management"
version = "0.1.0"
description = ""
authors = []
license = "BSD-3-Clause"
readme = "README.md"
packages = [{include = "course-management"}]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.0"
PyYAML = "^6.0.1"
bleach = "^6.1"
django-modeltranslation = "^0.19"
Markdown = "^3.6"
django-guardian = "^3.2"
psycopg2-binary = {version = "^2.9.9", optional = true}

[tool.poetry.extras]
pgsql = ["psycopg2-binary"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
